### ISSUE TITLE
Interessantes Projekt

### ISSUE THREAD

**Issue by andrex7** [elian15122000/TINF19C-PLCOpen-Editor#32]
Hi,
ich bin in der Softwareentwicklung im Bereich Automatisierungstechnik tätig und finde euer Projekt interessant für unser Produkt/Projekt.
Meldet euch bei mir: reinhold@promessmontage.de
Ich würde gern mehr erfahren, eine Demo sehen und wissen, wie weit ihr das Projekt vorantreiben wollt.
Ist auch eine Runtime geplant? :)

Grüße
Andre

**Comment by Mo-Official** [comment]
Hallo Andre,
Dieses Projekt ist ein Uni Projekt, das nicht für Produktion gedacht ist. Wir haben leider nicht vor langfristig dran zu entwickeln und wir wollen nur in Juni ein Prototype an dem Uni abgeben.
Falls Sie bis dahin noch dran Intresse haben und das Projekt übernehmen möchten, können wir das in Juni besprechen.

**Comment by andrex7** [comment]
Danke für das Feedback. Ich wünsche euch viel Erfolg bei eurem Projekt!
