### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Mo-Official** [elian15122000/TINF19C-PLCOpen-Editor#35]
Hier sollen alle Testfälle aufgelistet sein.

Vorgeschlagen für zum Testing wurde von Elian:
"Am besten Jasmine und Protractor (auf Angular zugeschnitten) nutzen (evtl. auch noch Jest)"

**Comment by Mo-Official** [comment]
Added some test cases in the Testplan

**Comment by elian15122000** [comment]
Created Layer and first entries

**Comment by elian15122000** [comment]
STP & STR sind fertig bis auf einige Lücken die noch von jeweiliger Person gefüllt werden sollten

**Comment by elian15122000** [comment]
Testing abgeschlossen
