### ISSUE TITLE
STP

### ISSUE THREAD

**Issue by FranziKo** [elian15122000/TINF19C-PLCOpen-Editor#5]

**Comment by elian15122000** [comment]
Ist so gut wie fertig, einige Lücken müssen von jeweils zuständiger Person gefüllt werden

**Comment by elian15122000** [comment]
STR ist Teil von STP

**Comment by Mo-Official** [comment]
Editor Testfälle in STP und STR sind ausgefüllt.
@elian15122000  schließt du den Issue?

**Comment by elian15122000** [comment]
STP und STR fertig abgeschlossen und ausgefüllt
